name: Release assets

on:
  push:
    tags:
      - '*.*.*'

jobs:
  assets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      
      - name: Build release assets
        run: make release
      
      - name: Upload release assets
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./docker-gen-*.tar.gz"]'
      
      - name: Cleanup release assets
        run: make dist-clean
